version: '3'

services:
  clock_app:
    # create image from Dockerfile in ./apps/clock_app
    build:
      context: ./apps/clock_app
    ports:
      - "5001:80"
  
  button_app:
    # create image from Dockerfile in ./apps/button_app
    build:
      context: ./apps/button_app
    ports:
      - "5002:80"
    # environment variables of the sevice
    environment:
      # public access to clock_app
      CLOCK_APP_URL: "http://172.22.0.3:8000"

# for containers speaking with each other
networks:
  default:
    name: clock_action_network